In [1]:
# 11. Filtering Data

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("globalAirQuality.csv")

df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [11]:
# Filtering of Data

df[df["aqi"] > 175]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
112,2025-11-09 10:25:17.554219,US,New York,40.713,-74.006,96.012,102.666,38.339,6.486,42.027,1.643,192,32.786,32.631,6.679
194,2025-11-12 20:25:17.554219,US,New York,40.713,-74.006,49.974,51.775,71.926,5.630,38.331,0.383,179,22.125,44.262,4.973
320,2025-11-18 02:25:17.554219,US,New York,40.713,-74.006,88.359,88.920,33.424,6.088,15.478,0.973,176,16.407,66.046,6.971
370,2025-11-05 04:25:17.554219,US,Los Angeles,34.052,-118.244,53.453,105.986,70.823,3.603,19.366,0.681,177,14.949,36.819,4.127
589,2025-11-14 07:25:17.554219,US,Los Angeles,34.052,-118.244,94.671,24.381,9.807,9.209,45.569,0.659,189,32.858,27.390,8.261
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,2025-11-10 01:25:17.554219,CH,Zurich,47.377,8.542,28.353,71.428,70.970,3.189,43.381,0.627,177,7.870,51.028,1.448
17774,2025-11-10 08:25:17.554219,CH,Zurich,47.377,8.542,88.273,59.940,56.835,7.710,3.285,0.690,176,18.013,83.859,6.823
17815,2025-11-12 01:25:17.554219,CH,Zurich,47.377,8.542,54.805,39.178,81.406,10.241,46.579,0.498,203,20.883,70.201,3.500
17885,2025-11-14 23:25:17.554219,CH,Zurich,47.377,8.542,52.162,35.304,76.076,6.090,44.849,0.557,190,6.196,32.675,4.792
17886,2025-11-15 00:25:17.554219,CH,Zurich,47.377,8.542,92.897,91.800,7.016,6.932,21.053,0.805,185,17.023,39.594,7.624

In [23]:
df[(df["aqi"] > 175) & (df["country"] == "IN")]

# df[df["aqi"] > 200]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6641,2025-11-11 11:25:17.554219,IN,Mumbai,19.076,72.878,37.509,80.830,73.015,6.403,60.263,0.890,182,12.845,73.544,2.302
6747,2025-11-15 21:25:17.554219,IN,Mumbai,19.076,72.878,62.908,19.589,77.649,7.903,65.652,0.919,194,32.153,53.831,1.480
6783,2025-11-17 09:25:17.554219,IN,Mumbai,19.076,72.878,95.929,61.409,48.361,7.268,37.606,1.331,191,37.271,83.946,6.947
6954,2025-11-09 12:25:17.554219,IN,Delhi,28.704,77.102,94.626,65.452,25.394,10.327,41.224,0.857,189,10.302,71.682,3.934
7024,2025-11-12 10:25:17.554219,IN,Delhi,28.704,77.102,44.382,45.774,78.190,4.611,5.395,0.991,195,34.274,49.015,3.470
7045,2025-11-13 07:25:17.554219,IN,Delhi,28.704,77.102,88.956,42.768,53.493,6.292,41.945,1.006,177,31.280,42.722,9.947
7178,2025-11-18 20:25:17.554219,IN,Delhi,28.704,77.102,18.817,52.704,72.507,7.433,59.090,0.655,181,18.714,60.559,7.946
7678,2025-11-09 16:25:17.554219,IN,Kolkata,22.573,88.364,91.538,46.013,24.842,3.966,75.040,1.273,183,19.667,52.976,3.175
7685,2025-11-09 23:25:17.554219,IN,Kolkata,22.573,88.364,11.105,66.409,71.661,7.369,65.319,0.320,179,5.601,60.852,4.241
8175,2025-11-15 09:25:17.554219,IN,Chennai,13.083,80.271,51.849,52.131,72.888,4.911,61.358,0.892,182,22.067,49.866,0.854

In [24]:
df[df["country"] == "IN"]["city"]

6480     Mumbai
6481     Mumbai
6482     Mumbai
6483     Mumbai
6484     Mumbai
         ...
8275    Chennai
8276    Chennai
8277    Chennai
8278    Chennai
8279    Chennai
Name: city, Length: 1800, dtype: object

In [40]:
df[(df["aqi"]>185) & (df["country"] == "IN")][["temperature", "city", "temperature"]]

      temperature    city  temperature
6747       32.153  Mumbai       32.153
6783       37.271  Mumbai       37.271
6954       10.302   Delhi       10.302
7024       34.274   Delhi       34.274