In [1]:
# 9. Data Concatenation with Pandas

In [2]:
import pandas as pd

In [4]:
df1 = pd.DataFrame({
    "id" : [1, 2, 3],
    "name" : ["Adom", "Eve", "Bob"]
})

df2 = pd.DataFrame({
    "id" : [4, 5, 6],
    "name" : ["Charlie", "Fester", "Gilian"]
})

   id     name
0   4  Charlie
1   5   Fester
2   6   Gilian

In [5]:
df1

   id  name
0   1  Adom
1   2   Eve
2   3   Bob

In [6]:
df2

   id     name
0   4  Charlie
1   5   Fester
2   6   Gilian

In [16]:
pd.concat([df1, df2]) # Row

   id     name
0   1     Adom
1   2      Eve
2   3      Bob
0   4  Charlie
1   5   Fester
2   6   Gilian

In [18]:
pd.concat([df1, df2], ignore_index= True)

   id     name
0   1     Adom
1   2      Eve
2   3      Bob
3   4  Charlie
4   5   Fester
5   6   Gilian

In [19]:
pd.concat([df1, df2], axis=1) # Column

   id  name  id     name
0   1  Adom   4  Charlie
1   2   Eve   5   Fester
2   3   Bob   6   Gilian